// const availableSources = [
//   {
//     id: 5,
//     name: "HubSpot",
//     description: "CRM and marketing automation platform",
//     icon: Database,
//     color: "bg-orange-100 text-orange-600",
//     category: "CRM",
//     popularity: 95,
//     setupTime: "5 minutes",
//     metrics: ["Leads", "Deals", "Contacts", "Pipeline Value"],
//     authType: "OAuth",
//     difficulty: "Easy",
//   },
//   {
//     id: 6,
//     name: "Facebook Ads",
//     description: "Social media advertising performance",
//     icon: Globe,
//     color: "bg-emerald-100 text-emerald-600",
//     category: "Advertising",
//     popularity: 88,
//     setupTime: "3 minutes",
//     metrics: ["Ad Spend", "Impressions", "CTR", "ROAS"],
//     authType: "OAuth",
//     difficulty: "Easy",
//   },
//   {
//     id: 7,
//     name: "Google Ads",
//     description: "Search advertising performance data",
//     icon: BarChart3,
//     color: "bg-green-100 text-green-600",
//     category: "Advertising",
//     popularity: 92,
//     setupTime: "3 minutes",
//     metrics: ["Cost", "Clicks", "Conversions", "Quality Score"],
//     authType: "OAuth",
//     difficulty: "Easy",
//   },
//   {
//     id: 8,
//     name: "Salesforce",
//     description: "Customer relationship management",
//     icon: Database,
//     color: "bg-emerald-100 text-emerald-600",
//     category: "CRM",
//     popularity: 85,
//     setupTime: "10 minutes",
//     metrics: ["Opportunities", "Accounts", "Activities", "Revenue"],
//     authType: "OAuth",
//     difficulty: "Medium",
//   },
//   {
//     id: 9,
//     name: "QuickBooks",
//     description: "Accounting and financial data",
//     icon: DollarSign,
//     color: "bg-emerald-100 text-emerald-600",
//     category: "Finance",
//     popularity: 78,
//     setupTime: "7 minutes",
//     metrics: ["Revenue", "Expenses", "Profit", "Cash Flow"],
//     authType: "OAuth",
//     difficulty: "Medium",
//   },
//   {
//     id: 10,
//     name: "Slack",
//     description: "Team communication and productivity",
//     icon: Users,
//     color: "bg-purple-100 text-purple-600",
//     category: "Productivity",
//     popularity: 65,
//     setupTime: "2 minutes",
//     metrics: ["Messages", "Active Users", "Channels", "Files Shared"],
//     authType: "OAuth",
//     difficulty: "Easy",
//   },
//   {
//     id: 11,
//     name: "Airtable",
//     description: "Database and project management",
//     icon: FileText,
//     color: "bg-yellow-100 text-yellow-600",
//     category: "Database",
//     popularity: 72,
//     setupTime: "5 minutes",
//     metrics: ["Records", "Tables", "Views", "Collaborators"],
//     authType: "API Key",
//     difficulty: "Medium",
//   },
//   {
//     id: 12,
//     name: "Calendly",
//     description: "Scheduling and appointment booking",
//     icon: Calendar,
//     color: "bg-indigo-100 text-indigo-600",
//     category: "Productivity",
//     popularity: 68,
//     setupTime: "3 minutes",
//     metrics: ["Bookings", "No-shows", "Meeting Types", "Availability"],
//     authType: "OAuth",
//     difficulty: "Easy",
//   },
// ];


// const connectedSources = [
//   {
//     id: 1,
//     name: "Google Analytics",
//     description: "Website traffic and user behavior data",
//     icon: BarChart3,
//     status: "connected",
//     lastSync: "2 minutes ago",
//     color: "bg-orange-100 text-orange-600",
//     metrics: ["Sessions", "Users", "Bounce Rate", "Conversion Rate"],
//   },
//   {
//     id: 2,
//     name: "Shopify",
//     description: "E-commerce sales and product data",
//     icon: ShoppingCart,
//     status: "connected",
//     lastSync: "5 minutes ago",
//     color: "bg-green-100 text-green-600",
//     metrics: ["Revenue", "Orders", "AOV", "Products Sold"],
//   },
//   {
//     id: 3,
//     name: "Stripe",
//     description: "Payment processing and revenue data",
//     icon: CreditCard,
//     status: "connected",
//     lastSync: "1 hour ago",
//     color: "bg-purple-100 text-purple-600",
//     metrics: ["Payments", "Refunds", "MRR", "Customer LTV"],
//   },
//   {
//     id: 4,
//     name: "Mailchimp",
//     description: "Email marketing campaigns and metrics",
//     icon: Mail,
//     status: "error",
//     lastSync: "Failed",
//     color: "bg-emerald-100 text-emerald-600",
//     metrics: ["Open Rate", "Click Rate", "Subscribers", "Campaigns"],
//   },
// ];